### ISSUE TITLE
插入图片没有效果，不知道是怎么回事

### ISSUE THREAD

**Issue by haoy1220** [mdnice/markdown-resume#15]

**Comment by guanpengchn** [comment]
请选择bug模板进行详细描述

**Comment by guanpengchn** [comment]
请详细描述下过程

**Comment by haoy1220** [comment]
我插入一个网格，然后点击它编辑，点右上角的图片图标，选了张照片，但是网格内并没有出现照片

**Comment by Sciroccogti** [comment]
我在自己部署的环境下也出现了一样的问题。

**Comment by endnowJ** [comment]
我也出现了这个问题

**Comment by haoy1220** [comment]
问题已经解决了，应该是示例的上传接口失效了，图片并没有上传上去。
解决办法：
自己搭建图床，上传图片获取到地址，再使用markdown的语法，在网格里插入就行了。
语法是这样的：![图片描述](图片地址)

**Comment by Sciroccogti** [comment]
是否可以像 #9 一样在脚本内修改图床？
