### ISSUE TITLE
简历填满一页打印时显示滚动条

### ISSUE THREAD

**Issue by qqxx6661** [mdnice/markdown-resume#20]
在用满一页的情况下，会出现滚动条。（实际还未超出一页）
![image](https://user-images.githubusercontent.com/12525295/79990327-801c4380-84e3-11ea-8d1f-e9e8e2e1eaab.png)

当然，如果删除几行，是不会显示滚动条的，但总觉得一页还没用满，在想要尽可能填写多点内容的情况下，会很郁闷。

目前用了临时的前端方法解决：

定位整个打印页元素

![image](https://user-images.githubusercontent.com/12525295/79990595-d38e9180-84e3-11ea-9fc0-b74d74a77910.png)

取消jss的height

![image](https://user-images.githubusercontent.com/12525295/79990633-dd17f980-84e3-11ea-889e-c9820d3a772f.png)

得到没有滚动条的页面，进行打印

![image](https://user-images.githubusercontent.com/12525295/79990693-ee610600-84e3-11ea-9631-3900e7f59efd.png)

这边不晓得有没有办法可以更优雅一些。我不是前端，所以不太懂这个的实现，如有冒犯见谅。

**Comment by mrdogge1** [comment]
我在输出为pdf的时候把边距设定成无，滚动条就没有了
