### ISSUE TITLE
本地json文件导入到浏览器不成功

### ISSUE THREAD

**Issue by LiYing0** [mdnice/markdown-resume#25]
把信息保存到本地，json文件里有信息，但是再导入到浏览器，无法解析本地的json文件，页面显示还是模板示例

**Comment by guanpengchn** [comment]
是不是md模式和富文本模式不对应

**Comment by LiYing0** [comment]
> 是不是md模式和富文本模式不对应

是的！切换了markdown模式成功了！谢谢
